#
# GFS API Composer HTTP Crud
#

# 
# Ubuntu 18.04.6 Bionic LTS
# 
@baseUrl = http://controller3:5000



###
# @name updateDHCPCompose
PUT {{baseUrl}}/api/v1.0/gfs1/compose/dhcp-compose.yml HTTP/1.1
Content-Type: application/json

{
  "version": "1.0",
  "name": "dhcp-compose.yml",
  "types": {
    "DHCPServiceType": {
      "name": "DHCPService",
      "version": 1,
      "extends": "#ServiceType",
      "implements": [
        "#DeployableType",
        "#RunnableType"
      ],
      "property": {
        "defaultLeaseTime": "string",
        "maxLeaseTime": "string",
        "configuredMachines": [
          "#MachineType"
        ]
      },
      "required": [
        "defaultLeaseTime",
        "maxLeaseTime"
      ]
    },
    "ServiceType": {
      "name": "Service",
      "version": 1,
      "property": {
        "name": "string"
      },
      "required": [
        "name"
      ]
    },
    "DeployableType": {
      "name": "Deployable",
      "version": 1,
      "property": {
        "isDeployed": "string",
        "target": "string"
      },
      "required": [
      ]
    },
    "RunnableType": {
      "name": "Runnable",
      "version": 1,
      "property": {
        "isRunning": "string",
        "status": "string"
      },
      "required": [
      ]
    },
    "MachineType": {
      "name": "Machine",
      "version": 1,
      "property": {
        "name": "string",
        "arch": "string",
        "memory": "string",
        "cpus": "string",
        "cores": "string",
        "kernel": "string",
        "version": "string",
        "machine": "string",
        "processor": "string",
        "platform": "string",
        "system": "string",
        "vendor": "string",
        "description": "string",
        "release": "string",
        "codename": "string",
        "configuredInterfaces": [
          "#NetDeviceType"
        ],
        "defaultInterface": [
          "#NetDeviceType"
        ]
      },
      "required": [
        "name",
        "arch",
        "memory",
        "cpus",
        "cores",
        "kernel",
        "version",
        "machine",
        "processor",
        "platform",
        "system",
        "vendor",
        "description",
        "release",
        "codename"
      ]
    },
    "NetDeviceType": {
      "name": "NetDevice",
      "version": 1,
      "property": {
        "name": "string",
        "hwaddr": "string",
        "addresses": [
          "#IpType"
        ]
      },
      "required": [
        "name",
        "hwaddr"
      ]
    },
    "IpType": {
      "name": "Ip",
      "version": 1,
      "property": {
        "name": "string",
        "address": "string"
      },
      "required": [
        "name",
        "address"
      ]
    }
  },
  "DHCPServiceTypes": {
    "nasdhcp1": {
      "data": {
        "name": "nasdhcp1",
        "defaultLeaseTime": "100",
        "maxLeaseTime": "200",
        "configuredMachines": [
          "#ship",
          "#desk",
          "#cent",
          "#serv",
          "#java",
          "#slacker",
          "#kube"
        ]
      }
    }
  },
  "MachineTypes": {
    "ship": {
      "data": {
        "name": "ship",
        "arch": "x86_64",
        "memory": "16G",
        "cpus": "1",
        "cores": "4",
        "kernel": "5.4.0-84-generic",
        "version": "94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021",
        "machine": "x86_64",
        "processor": "x86_64",
        "platform": "x86_64",
        "system": "GNU/Linux",
        "vendor": "Ubuntu",
        "description": "Ubuntu 20.04.3 LTS",
        "release": "20.04",
        "codename": "focal",
        "configuredInterfaces": [
          "#ship-ens18",
          "#ship-ens19"
        ],
        "defaultInterface": [
          "#ship-ens18"
        ]
      }
    },
    "desk": {
      "data": {
        "name": "desk",
        "arch": "x86_64",
        "memory": "8G",
        "cpus": "1",
        "cores": "2",
        "kernel": "5.11.0-34-generic",
        "version": "36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021",
        "machine": "x86_64",
        "processor": "x86_64",
        "platform": "x86_64",
        "system": "GNU/Linux",
        "vendor": "Ubuntu",
        "description": "Ubuntu 20.04.3 LTS",
        "release": "20.04",
        "codename": "focal",
        "configuredInterfaces": [
          "#desk-ens18",
          "#desk-ens19"
        ],
        "defaultInterface": [
          "#desk-ens18"
        ]
      }
    },
    "cent": {
      "data": {
        "name": "cent",
        "arch": "x86_64",
        "memory": "4G",
        "cpus": "1",
        "cores": "2",
        "kernel": "3.10.0-1160.42.2.el7.x86_64",
        "version": "1 SMP Tue Sep 7 14:49:57 UTC 2021",
        "machine": "x86_64",
        "processor": "x86_64",
        "platform": "x86_64",
        "system": "GNU/Linux",
        "vendor": "CentOS",
        "description": "CentOS Linux release 7.9.2009 (Core)",
        "release": "7.9.2009",
        "codename": "Core",
        "configuredInterfaces": [
          "#cent-eth0"
        ],
        "defaultInterface": [
          "#cent-eth0"
        ]
      }
    },
    "serv": {
      "data": {
        "name": "serv",
        "arch": "x86_64",
        "memory": "4G",
        "cpus": "1",
        "cores": "2",
        "kernel": "4.15.0-156-generic",
        "version": "163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021",
        "machine": "x86_64",
        "processor": "x86_64",
        "platform": "x86_64",
        "system": "GNU/Linux",
        "vendor": "Ubuntu",
        "description": "Ubuntu 18.04.6 LTS",
        "release": "18.04",
        "codename": "bionic",
        "configuredInterfaces": [
          "#serv-ens18"
        ],
        "defaultInterface": [
          "#serv-ens18"
        ]
      }
    },
    "java": {
      "data": {
        "name": "java",
        "arch": "x86_64",
        "memory": "4G",
        "cpus": "1",
        "cores": "2",
        "kernel": "3.10.0-1160.42.2.el7.x86_64",
        "version": "1 SMP Tue Sep 7 14:49:57 UTC 2021",
        "machine": "x86_64",
        "processor": "x86_64",
        "platform": "x86_64",
        "system": "GNU/Linux",
        "vendor": "CentOS",
        "description": "CentOS Linux release 7.9.2009 (Core)",
        "release": "7.9.2009",
        "codename": "Core",
        "configuredInterfaces": [
          "#java-eth0"
        ],
        "defaultInterface": [
          "#java-eth0"
        ]
      }
    },
    "slacker": {
      "data": {
        "name": "slacker",
        "arch": "Common KVM processor",
        "memory": "4G",
        "cpus": "1",
        "cores": "2",
        "kernel": "5.13.12",
        "version": "1 SMP Wed Aug 18 10:10:09 CDT 2021",
        "machine": "x86_64",
        "processor": "Common KVM processor",
        "platform": "GenuineIntel",
        "system": "GNU/Linux",
        "vendor": "Slackware",
        "description": "Slackware 15.0",
        "release": "15.0",
        "codename": "15.0",
        "configuredInterfaces": [
          "#slacker-eth0"
        ],
        "defaultInterface": [
          "#slacker-eth0"
        ]
      }
    },
    "kube": {
      "data": {
        "name": "kube",
        "arch": "x86_64",
        "memory": "16G",
        "cpus": "1",
        "cores": "4",
        "kernel": "5.4.0-86-generic",
        "version": "97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021",
        "machine": "x86_64",
        "processor": "x86_64",
        "platform": "x86_64",
        "system": "GNU/Linux",
        "vendor": "Ubuntu",
        "description": "Ubuntu 20.04.3 LTS",
        "release": "20.04",
        "codename": "focal",
        "configuredInterfaces": [
          "#kube-ens18",
          "#kube-ens19"
        ],
        "defaultInterface": [
          "#kube-ens18"
        ]
      }
    }
  },
  "NetDeviceTypes": {
    "ship-ens18": {
      "data": {
        "name": "ship-ens18",
        "hwaddr": "96:72:db:18:bd:9f",
        "addresses": [
          "#ipa141"
        ]
      }
    },
    "ship-ens19": {
      "data": {
        "name": "ship-ens19",
        "hwaddr": "36:2f:ea:44:71:81",
        "addresses": [
          "#ipb104"
        ]
      }
    },
    "desk-ens18": {
      "data": {
        "name": "desk-ens18",
        "hwaddr": "76:7c:d9:67:2d:ca",
        "addresses": [
          "#ipa212"
        ]
      }
    },
    "desk-ens19": {
      "data": {
        "name": "desk-ens19",
        "hwaddr": "f2:59:80:ce:8a:b9",
        "addresses": [
          "#ipb247"
        ]
      }
    },
    "cent-eth0": {
      "data": {
        "name": "cent-eth0",
        "hwaddr": "36:95:64:4f:00:48",
        "addresses": [
          "#ipa142"
        ]
      }
    },
    "serv-ens18": {
      "data": {
        "name": "serv-ens18",
        "hwaddr": "56:d8:17:bf:c5:f7",
        "addresses": [
          "#ipa145"
        ]
      }
    },
    "java-eth0": {
      "data": {
        "name": "java-eth0",
        "hwaddr": "72:8b:f9:62:ec:59",
        "addresses": [
          "#ipa92"
        ]
      }
    },
    "slacker-eth0": {
      "data": {
        "name": "slacker-eth0",
        "hwaddr": "4a:7c:b0:37:0b:e1",
        "addresses": [
          "#ipa154"
        ]
      }
    },
    "kube-ens18": {
      "data": {
        "name": "kube-ens18",
        "hwaddr": "4a:0b:5d:1d:b1:43",
        "addresses": [
          "#ipa158"
        ]
      }
    },
    "kube-ens19": {
      "data": {
        "name": "kube-ens19",
        "hwaddr": "22:b1:1f:e5:ca:f4",
        "addresses": [
          "#ipb104"
        ]
      }
    }
  },
  "IpTypes": {
    "ipa141": {
      "data": {
        "name": "ipa141",
        "address": "192.168.0.141"
      }
    },
    "ipb104": {
      "data": {
        "name": "ipb104",
        "address": "10.88.88.104"
      }
    },
    "ipa212": {
      "data": {
        "name": "ipa212",
        "address": "192.168.0.212"
      }
    },
    "ipb247": {
      "data": {
        "name": "ipb247",
        "address": "10.88.88.247"
      }
    },
    "ipa142": {
      "data": {
        "name": "ipa142",
        "address": "192.168.0.142"
      }
    },
    "ipa145": {
      "data": {
        "name": "ipa145",
        "address": "192.168.0.145"
      }
    },
    "ipa92": {
      "data": {
        "name": "ipa92",
        "address": "192.168.0.92"
      }
    },
    "ipa154": {
      "data": {
        "name": "ipa154",
        "address": "192.168.0.154"
      }
    },
    "ipa158": {
      "data": {
        "name": "ipa158",
        "address": "192.168.0.158"
      }
    },
    "ipb104": {
      "data": {
        "name": "ipb104",
        "address": "10.88.88.104"
      }
    }
  },
  "templates": {
  },
  "links": {
  }
}
