#
# GFS API Composer HTTP Crud
#

# 
# Ubuntu 18.04.6 Bionic LTS
# 
@baseUrl = http://controller3:5000



###
# @name updateDHCPCompose
PUT {{baseUrl}}/api/v1.0/gfs1/compose/dhcp-compose.yml HTTP/1.1
Content-Type: application/json

{
  "version": "1.0",
  "name": "dhcp-compose.yml",
  "types": {
    "DHCPServiceType": {
      "name": "DHCPService",
      "version": 1,
      "extends": "#ServiceType",
      "property": {
        "name": "string"
      },
      "required": [
        "name"
      ]
    },
    "ServiceType": {
      "name": "Service",
      "version": 1,
      "property": {
        "name": "string"
      },
      "required": [
        "name"
      ]
    },
    "MachineType": {
      "name": "Machine",
      "version": 1,
      "property": {
        "name": "string"
      },
      "required": [
        "name"
      ]
    }
  },
  "templates": {
  },
  "links": {
  }
}
