#
# GFS API Composer HTTP Crud
#

# 
# Ubuntu 18.04.6 Bionic LTS
# 
@baseUrl = http://controller3:5000



###
# @name updateDHCPCompose
PUT {{baseUrl}}/api/v1.0/gfs1/compose/dhcp-compose.yml HTTP/1.1
Content-Type: application/json

{
  "version": "1.0",
  "name": "dhcp-compose.yml",
  "types": {
    "DHCPServiceType": {
      "name": "DHCPService",
      "version": 1,
      "extends": "#ServiceType",
      "property": {
        "name": "string",
        "defaultLeaseTime": "string",
        "maxLeaseTime": "string",
        "configuredMachines": [
          "#MachineType"
        ]
      },
      "required": [
        "name",
        "defaultLeaseTime",
        "maxLeaseTime"
      ]
    },
    "ServiceType": {
      "name": "Service",
      "version": 1,
      "property": {
        "name": "string"
      },
      "required": [
        "name"
      ]
    },
    "DeployableType": {
      "name": "Deployable",
      "version": 1,
      "property": {
        "isDeployed": "string",
        "target": "string"
      },
      "required": [
      ]
    },
    "RunnableType": {
      "name": "Runnable",
      "version": 1,
      "property": {
        "isRunning": "string",
        "status": "string"
      },
      "required": [
      ]
    },
    "MachineType": {
      "name": "Machine",
      "version": 1,
      "property": {
        "name": "string",
        "arch": "string",
        "memory": "string",
        "cpus": "string",
        "cores": "string",
        "kernel": "string",
        "version": "string",
        "machine": "string",
        "processor": "string",
        "platform": "string",
        "system": "string",
        "vendor": "string",
        "description": "string",
        "release": "string",
        "codename": "string",
        "configuredInterfaces": [
          "#NetDeviceType"
        ],
        "defaultInterface": [
          "#NetDeviceType"
        ]
      },
      "required": [
        "name",
        "arch",
        "memory",
        "cpus",
        "cores",
        "kernel",
        "version",
        "machine",
        "processor",
        "platform",
        "system",
        "vendor",
        "description",
        "release",
        "codename"
      ]
    },
    "NetDeviceType": {
      "name": "NetDevice",
      "version": 1,
      "property": {
        "name": "string",
        "hwaddr": "string",
        "addresses": [
          "#IpType"
        ]
      },
      "required": [
        "name",
        "hwaddr"
      ]
    },
    "IpType": {
      "name": "Ip",
      "version": 1,
      "property": {
        "name": "string",
        "address": "string"
      },
      "required": [
        "name",
        "address"
      ]
    }
  },
  "templates": {
  },
  "links": {
  }
}
