#
# GFS API Composer HTTP Crud
#

# 
# Ubuntu 18.04.6 Bionic LTS
# 
@baseUrl = http://controller3:5000



###
# @name deleteDHCPCompose
DELETE {{baseUrl}}/api/v1.0/gfs1/compose/dhcpcompose1/autonomic-compose.yml HTTP/1.1
Content-Type: application/json

{
}
